require 'lfs/insim/basic_types'
require 'lfs/insim/complex_types'
require 'lfs/insim/packet_factory'
require 'lfs/insim/packet/base'
# Packet
require "lfs/insim/packet/communication"
require "lfs/insim/packet/relay"
require "lfs/insim/packet/race"
require "lfs/insim/packet/position"
