require 'lfs/insim/basic_types'
require 'lfs/insim/complex_types'
require 'lfs/insim/packet_factory'
require 'lfs/insim/packet/base'
# Packet
require "lfs/insim/packet/communication"
require "lfs/insim/packet/relay"
require "lfs/insim/packet/race"
require "lfs/insim/packet/position"
require "lfs/insim/packet/camera"
require "lfs/insim/packet/message"
require "lfs/insim/packet/connection"
require "lfs/insim/packet/autocross"
require "lfs/insim/packet/button"
